package com.ztj.tourist.dao.mapper;

import com.ztj.tourist.dao.domain.Diary;
import com.ztj.tourist.dao.domain.DiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    long countByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    List<Diary> selectByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    Diary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    int updateByExample(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    int updateByPrimaryKey(Diary record);
}