package com.ztj.tourist.dao.domain;

import java.util.Date;

public class Diary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.id
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.title
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.content
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.author
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.summary_picture
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private String summaryPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.summary_content
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private String summaryContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.type
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.create_time
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary.update_time
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.id
     *
     * @return the value of diary.id
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.id
     *
     * @param id the value for diary.id
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.title
     *
     * @return the value of diary.title
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.title
     *
     * @param title the value for diary.title
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.content
     *
     * @return the value of diary.content
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.content
     *
     * @param content the value for diary.content
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.author
     *
     * @return the value of diary.author
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.author
     *
     * @param author the value for diary.author
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.summary_picture
     *
     * @return the value of diary.summary_picture
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public String getSummaryPicture() {
        return summaryPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.summary_picture
     *
     * @param summaryPicture the value for diary.summary_picture
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setSummaryPicture(String summaryPicture) {
        this.summaryPicture = summaryPicture == null ? null : summaryPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.summary_content
     *
     * @return the value of diary.summary_content
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public String getSummaryContent() {
        return summaryContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.summary_content
     *
     * @param summaryContent the value for diary.summary_content
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setSummaryContent(String summaryContent) {
        this.summaryContent = summaryContent == null ? null : summaryContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.type
     *
     * @return the value of diary.type
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.type
     *
     * @param type the value for diary.type
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.create_time
     *
     * @return the value of diary.create_time
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.create_time
     *
     * @param createTime the value for diary.create_time
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary.update_time
     *
     * @return the value of diary.update_time
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary.update_time
     *
     * @param updateTime the value for diary.update_time
     *
     * @mbg.generated Wed Nov 20 14:28:06 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}